# https://github.com/erikdubbelboer/phpRedisAdmin/blob/master/docker-compose.yml
version: "3.7"
services:
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./data:/data
  
  redisweb:
    image: erikdubbelboer/phpredisadmin
    ports:
      - 63791:80
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
    links:
      - redis